package restapi.model;
// Generated Nov 11, 2018 7:08:40 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Markerinfo generated by hbm2java
 */
@Entity
@Table(name = "markerinfo", schema = "public")
public class Markerinfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private String rs;
	private String alleles;
	private String chrom;
	private String pos;

	public Markerinfo() {
	}

	public Markerinfo(long id) {
		this.id = id;
	}

	public Markerinfo(long id, String rs, String alleles, String chrom, String pos) {
		this.id = id;
		this.rs = rs;
		this.alleles = alleles;
		this.chrom = chrom;
		this.pos = pos;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "rs")
	public String getRs() {
		return this.rs;
	}

	public void setRs(String rs) {
		this.rs = rs;
	}

	@Column(name = "alleles")
	public String getAlleles() {
		return this.alleles;
	}

	public void setAlleles(String alleles) {
		this.alleles = alleles;
	}

	@Column(name = "chrom")
	public String getChrom() {
		return this.chrom;
	}

	public void setChrom(String chrom) {
		this.chrom = chrom;
	}

	@Column(name = "pos")
	public String getPos() {
		return this.pos;
	}

	public void setPos(String pos) {
		this.pos = pos;
	}

}
