package restapi.model;
// Generated Nov 11, 2018 7:08:40 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OtherPlant generated by hbm2java
 */
@Entity
@Table(name = "other_plant", schema = "public")
public class OtherPlant implements java.io.Serializable {

	private OtherPlantId id;

	public OtherPlant() {
	}

	public OtherPlant(OtherPlantId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "value", column = @Column(name = "value")) })
	public OtherPlantId getId() {
		return this.id;
	}

	public void setId(OtherPlantId id) {
		this.id = id;
	}

}
