package restapi.model;
// Generated Nov 11, 2018 7:08:40 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OtherSeed generated by hbm2java
 */
@Entity
@Table(name = "other_seed", schema = "public")
public class OtherSeed implements java.io.Serializable {

	private long id;
	private String value;
	private String description;

	public OtherSeed() {
	}

	public OtherSeed(long id) {
		this.id = id;
	}

	public OtherSeed(long id, String value, String description) {
		this.id = id;
		this.value = value;
		this.description = description;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
