package restapi.model;
// Generated Nov 11, 2018 7:08:40 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Snp generated by hbm2java
 */
@Entity
@Table(name = "snp", schema = "public")
public class Snp implements java.io.Serializable {

	private String id;
	private String snp;

	public Snp() {
	}

	public Snp(String id) {
		this.id = id;
	}

	public Snp(String id, String snp) {
		this.id = id;
		this.snp = snp;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "snp", length = 42291)
	public String getSnp() {
		return this.snp;
	}

	public void setSnp(String snp) {
		this.snp = snp;
	}

}
